//
// get_in_the_wayL.c
//
// Copyright (c) 2013 Suit Bots 4628
//

#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          HandL,         tmotorNXT, openLoop, reversed, encoder)
#pragma config(Motor,  motorB,          HandR,         tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     ML,            tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     MR,            tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     ScissorL1,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     ScissorR1,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     ScissorL2,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     ScissorR2,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     fork_prop,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_4,    fork_drop,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    HandLR,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_6,    hand_vertical,        tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Autonomous_Base.h"
#include "JoystickDriver.c"

// This autonomous' goal is to get to the opponent's platform and get in the way
//
// +----------------------+
// | \                  / |     R - Starting point
// |   \       ......./.R |     . - Robot Path
// |     +----.-----+     |     S - Raise Scissor
// |     |   .      |     |     / or \ - team boundries
// |     |  S       |     |     + or - - borders
// |     |          |     |
// |     |          |     |
// |     +----------+     |
// |   /              \   |
// | /                  \ |
// +----------------------+
//

void resetMotors (char name, char name1) {
	nMotorEncoder[name] = 0;
	nMotorEncoder[name1] = 0;
}

task main()  { // the Trues and Falses might have to be flipped
	initializeRobot(HandL, HandR, ML, MR, ScissorL1, ScissorR1);

	waitForStart();
	while (nMotorEncoder[ML] < 14000 && nMotorEncoder[MR] < 14000) {
		motor[ML] = 75;
		motor[MR] = 75;
	}
	resetMotors(ML, MR);

	while (nMotorEncoder[ML] < 3333 && nMotorEncoder[MR] > -3333) {
		motor[ML] = 75;
		motor[MR] = -75;
	}

	resetMotors(ML, MR);

	while (nMotorEncoder[ML] < 4250 && nMotorEncoder[MR] < 4250) {
		motor[ML] = 75;
		motor[MR] = 75;
	}
	resetMotors(ML, MR);
}
